import { type NextRequest, NextResponse } from 'next/server';
import { createSupabaseAuthClient } from '@/lib/supabase/auth-client';
import { env } from '@/lib/env';

/**
 * GET /api/auth/confirm?token_hash=...&type=signup
 *
 * Called when a user clicks the email verification link we send via Resend.
 * Validates the token with Supabase and redirects to the login page.
 */
export async function GET(req: NextRequest): Promise<NextResponse> {
  const { searchParams } = new URL(req.url);
  const tokenHash = searchParams.get('token_hash');
  const type = searchParams.get('type');

  const appUrl = env.NEXT_PUBLIC_APP_URL;

  if (!tokenHash || !type) {
    return NextResponse.redirect(new URL('/login?verified=error', appUrl));
  }

  const supabase = createSupabaseAuthClient();

  const { error } = await supabase.auth.verifyOtp({
    token_hash: tokenHash,
    // 'signup' is the OTP type generated by admin.generateLink({ type: 'signup' })
    type: type as 'signup',
  });

  if (error) {
    return NextResponse.redirect(new URL('/login?verified=error', appUrl));
  }

  return NextResponse.redirect(new URL('/login?verified=true', appUrl));
}
