'use client';

import { useEffect, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { useTranslations } from 'next-intl';
import { AlertCircle } from 'lucide-react';
import { signIn } from 'next-auth/react';
import { authApi } from '@/services/auth-api';
import { Button } from '@/components/ui/button';

type Phase = 'detecting' | 'authenticating' | 'linking' | 'error';

/**
 * Telegram Mini App entry point — /tg
 *
 * Flow:
 *  1. Detect window.Telegram.WebApp (SDK must be loaded via layout Script tag).
 *  2. POST initData to /api/auth/telegram → validate HMAC server-side.
 *  3. Exchange the returned hashed_token for a Supabase session.
 *  4. Redirect to callbackUrl (default: /dashboard).
 *
 * If the page is opened outside Telegram, redirect to the regular /login page
 * (preserving callbackUrl so the user lands on the right page after login).
 */
export default function TelegramEntryPage() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const t = useTranslations();
  const [phase, setPhase] = useState<Phase>('detecting');
  const [errorMsg, setErrorMsg] = useState('');

  useEffect(() => {
    const callbackUrl = searchParams.get('callbackUrl') || '/dashboard';

    async function authenticate() {
      // Wait one tick so the Telegram SDK (loaded beforeInteractive) is ready.
      await new Promise((r) => setTimeout(r, 50));

      const initData = window.Telegram?.WebApp?.initData;

      if (!initData) {
        // Not inside Telegram (or SDK not ready) — send to regular login.
        const loginUrl = `/login${callbackUrl !== '/dashboard' ? `?callbackUrl=${encodeURIComponent(callbackUrl)}` : ''}`;
        router.replace(loginUrl);
        return;
      }

      const tg = window.Telegram!.WebApp;
      tg.ready();
      tg.expand();

      // Auto-set UI language based on Telegram user's language_code
      const telegramLanguage = window.Telegram?.WebApp?.initDataUnsafe?.user?.language_code;
      if (telegramLanguage) {
        // Map Telegram language codes to our supported locales
        const supportedLocales: Record<string, string> = {
          ru: 'ru',
          en: 'en',
          // Add other language codes that map to 'ru' or 'en' as needed
        };
        const locale = supportedLocales[telegramLanguage] || 'en';
        // Set cookie for language preference
        document.cookie = `NEXT_LOCALE=${locale}; path=/; max-age=${60 * 60 * 24 * 365}`;
      }

      // Check for account-linking start_param (generated by Settings → Connect Telegram)
      const startParam = window.Telegram?.WebApp?.initDataUnsafe?.start_param;

      if (startParam?.startsWith('link_')) {
        // ── Linking flow ────────────────────────────────────────────────────
        const linkToken = startParam.slice('link_'.length);
        setPhase('linking');

        try {
          const { sessionToken, overLimit } = await authApi.linkTelegramAccount(
            initData,
            linkToken,
          );
          const result = await signIn('telegram', { sessionToken, redirect: false });
          if (!result?.ok) throw new Error(result?.error ?? 'Link sign-in failed');
          // Redirect to settings; pass overLimit flag so the settings page can warn the user.
          window.location.href = '/settings' + (overLimit ? '?overLimit=1' : '');
        } catch (err) {
          const msg = err instanceof Error ? err.message : t('telegram.linkFailed');
          setErrorMsg(msg);
          setPhase('error');
        }
        return;
      }

      // ── Normal authentication flow ──────────────────────────────────────
      setPhase('authenticating');

      try {
        // 1. Validate initData on the server — server verifies the Telegram
        //    HMAC and returns a short-lived signed token.
        const { sessionToken } = await authApi.exchangeTelegramInitData(initData);

        // 2. Exchange for a NextAuth session (same cookie as email users).
        //    This eliminates the Supabase browser-client race condition.
        const result = await signIn('telegram', { sessionToken, redirect: false });
        if (!result?.ok) throw new Error(result?.error ?? 'Sign-in failed');

        // 3. Hard navigate — NextAuth has already set the session cookie so
        //    the middleware will see it on the very next request.
        window.location.href = callbackUrl;
      } catch (err) {
        const msg = err instanceof Error ? err.message : t('telegram.authenticationFailed');
        setErrorMsg(msg);
        setPhase('error');
      }
    }

    void authenticate();
  }, [router, searchParams, t]);

  if (phase === 'error') {
    return (
      <main className="flex min-h-screen flex-col items-center justify-center px-6 text-center">
        <AlertCircle className="mb-4 h-12 w-12 text-red-600" />
        <h1 className="mb-2 text-lg font-semibold text-gray-900">{t('telegram.signinFailed')}</h1>
        <p className="mb-6 text-sm text-gray-500">{errorMsg}</p>
        <Button onClick={() => router.replace('/login')}>{t('telegram.useEmailLogin')}</Button>
      </main>
    );
  }

  return (
    <main className="flex min-h-screen flex-col items-center justify-center gap-4 px-6 text-center">
      <div className="h-10 w-10 animate-spin rounded-full border-4 border-primary border-t-transparent" />
      <p className="text-sm text-gray-500">
        {phase === 'detecting'
          ? t('telegram.starting')
          : phase === 'linking'
            ? t('telegram.linking')
            : t('telegram.signingYouIn')}
      </p>
    </main>
  );
}
