import { NextResponse } from 'next/server';
import { z } from 'zod';
import { createHmac } from 'crypto';
import { withApiHandler } from '@/lib/api/handler';
import { AuthError, ValidationError } from '@/lib/errors';
import { supabaseAdmin } from '@/lib/supabase/admin';
import { env } from '@/lib/env';
import { logger } from '@/lib/logger';
import { getUserPlan } from '@/lib/subscription-utils';

const bodySchema = z.object({
  initData: z.string().min(1),
  linkToken: z.string().min(1),
});

interface TelegramUser {
  id: number;
  first_name: string;
  last_name?: string;
  username?: string;
}

/**
 * Validates Telegram initData HMAC signature.
 * Duplicated from /api/auth/telegram/route.ts — shared extraction is a future
 * refactor; kept local to avoid cross-route coupling for now.
 */
function validateTelegramInitData(initData: string, botToken: string): TelegramUser {
  const params = new URLSearchParams(initData);
  const hash = params.get('hash');

  if (!hash) {
    throw new AuthError({ message: 'Missing hash in Telegram initData' });
  }

  params.delete('hash');

  const sortedParams = [...params.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([key, value]) => `${key}=${value}`)
    .join('\n');

  const secretKey = createHmac('sha256', 'WebAppData').update(botToken).digest();
  const expectedHash = createHmac('sha256', secretKey).update(sortedParams).digest('hex');

  if (expectedHash !== hash) {
    throw new AuthError({ message: 'Telegram initData HMAC verification failed' });
  }

  const userParam = params.get('user');
  if (!userParam) {
    throw new AuthError({ message: 'No user in Telegram initData' });
  }

  return JSON.parse(userParam) as TelegramUser;
}

/**
 * Verifies a link token generated by POST /api/profile/telegram-link-token.
 * Returns the userId embedded in the token, or throws on tampered / expired tokens.
 */
function verifyLinkToken(token: string): string {
  // HMAC-SHA256 base64url is always exactly 43 characters.
  // The token is payload + sig with no separator (Telegram startapp forbids dots).
  const SIG_LEN = 43;
  if (token.length <= SIG_LEN) throw new AuthError({ message: 'Malformed link token' });

  const payload = token.slice(0, -SIG_LEN);
  const sig = token.slice(-SIG_LEN);

  const secret = env.NEXTAUTH_SECRET ?? env.SUPABASE_SERVICE_KEY;
  const expectedSig = createHmac('sha256', secret).update(payload).digest('base64url');

  if (sig !== expectedSig) {
    throw new AuthError({ message: 'Invalid link token signature' });
  }

  const { userId, exp } = JSON.parse(Buffer.from(payload, 'base64url').toString()) as {
    userId: string;
    exp: number;
  };

  if (Date.now() > exp) {
    throw new AuthError({
      message: 'Link token has expired — please generate a new one from Settings',
    });
  }

  return userId;
}

/**
 * POST /api/profile/link-telegram
 *
 * Public endpoint called from within the Telegram Mini App.
 * Body: { initData: string, linkToken: string }
 *
 * Flow:
 *  1. Verify linkToken → get web userId
 *  2. Validate Telegram HMAC → get telegramId
 *  3. If web account already linked to this same telegramId → idempotent success
 *  4. If web account already linked to a DIFFERENT telegramId → conflict error
 *  5. If another profile holds this telegramId:
 *     - Stub (telegram_*@noreply.clario.app) with no themes → delete stub & proceed
 *     - Otherwise → conflict error (manual merge required)
 *  6. Stamp telegram_id on the web account
 *  7. Issue a signed session token for the web account
 */
export const POST = withApiHandler(async (req) => {
  if (!env.TELEGRAM_BOT_TOKEN) {
    throw new AuthError({ message: 'Telegram auth is not configured on this server' });
  }

  const body = bodySchema.safeParse(await req.json());
  if (!body.success) {
    throw new ValidationError({ message: 'initData and linkToken are required' });
  }

  const userId = verifyLinkToken(body.data.linkToken);
  const telegramUser = validateTelegramInitData(body.data.initData, env.TELEGRAM_BOT_TOKEN);
  const telegramId = String(telegramUser.id);

  // Tracks whether the merged theme count exceeds the web user's plan limit.
  let overLimit = false;

  // ── 1. Check if the web account already has a telegram_id ──────────────────
  const { data: webProfile } = await supabaseAdmin
    .from('profiles')
    .select('telegram_id')
    .eq('id', userId)
    .maybeSingle();

  if (webProfile?.telegram_id) {
    if (webProfile.telegram_id !== telegramId) {
      throw new AuthError({
        message: 'Your account is already linked to a different Telegram account',
      });
    }
    // Same telegramId → already linked, fall through to session issuance (idempotent).
  } else {
    // ── 2. Check if another profile already holds this telegramId ─────────────
    const { data: existingTgProfile } = await supabaseAdmin
      .from('profiles')
      .select('id')
      .eq('telegram_id', telegramId)
      .neq('id', userId)
      .maybeSingle();

    if (existingTgProfile) {
      const { data: stubLookup } = await supabaseAdmin.auth.admin.getUserById(existingTgProfile.id);
      const email = stubLookup.user?.email ?? '';
      // More forgiving stub detection: any email starting with telegram_ and containing @noreply
      const isStub = email.startsWith('telegram_') && email.includes('@noreply');

      logger.info(
        { existingProfileId: existingTgProfile.id, email, isStub, telegramId },
        'Checking if existing profile is a stub',
      );

      // Always check for themes, regardless of stub status — empty profiles can be safely removed
      const { count: themeCount } = await supabaseAdmin
        .from('themes')
        .select('id', { count: 'exact', head: true })
        .eq('user_id', existingTgProfile.id);

      const hasThemes = (themeCount ?? 0) > 0;

      if (hasThemes && !isStub) {
        // A real (non-stub) web account owns this telegramId — genuine conflict, cannot auto-resolve.
        logger.warn(
          { existingProfileId: existingTgProfile.id, themeCount },
          'Non-stub account with themes owns this telegramId — conflict',
        );
        throw new AuthError({
          message: 'This Telegram account is already linked to a different web account',
        });
      }

      if (hasThemes && isStub) {
        // Stub has themes — merge them into the web account before deleting.
        logger.info(
          { stubId: existingTgProfile.id, webUserId: userId, themeCount },
          'Merging stub themes into web account',
        );
        // 1. Move all themes (cards + sources cascade via theme_id FK, not user_id)
        await supabaseAdmin
          .from('themes')
          .update({ user_id: userId })
          .eq('user_id', existingTgProfile.id);
        // 2. Move bookmarked cards (ignore conflicts — web user may already have same ones)
        const { data: stubBookmarks } = await supabaseAdmin
          .from('bookmarked_cards')
          .select('card_id')
          .eq('user_id', existingTgProfile.id);
        if (stubBookmarks?.length) {
          await supabaseAdmin.from('bookmarked_cards').upsert(
            stubBookmarks.map((b) => ({ user_id: userId, card_id: b.card_id })),
            { onConflict: 'user_id,card_id', ignoreDuplicates: true },
          );
        }

        // Check combined theme count vs plan limit (set flag, report in response)
        const [{ count: mergedThemeCount }, planInfo] = await Promise.all([
          supabaseAdmin
            .from('themes')
            .select('id', { count: 'exact', head: true })
            .eq('user_id', userId),
          getUserPlan(userId),
        ]);
        overLimit = planInfo.maxThemes !== null && (mergedThemeCount ?? 0) > planInfo.maxThemes;
      }

      // Empty or just-merged stub — safe to remove (subscription/usage rows cascade-delete)
      logger.info(
        { existingProfileId: existingTgProfile.id, isStub, hadThemes: hasThemes },
        'Deleting stub account after merge',
      );
      await supabaseAdmin.auth.admin.deleteUser(existingTgProfile.id);
    }

    // ── 3. Stamp telegram_id on the web account ──────────────────────────────
    await supabaseAdmin.from('profiles').update({ telegram_id: telegramId }).eq('id', userId);
  }

  // ── 4. Issue a signed session token for the web account ───────────────────
  const { data: profile } = await supabaseAdmin
    .from('profiles')
    .select('display_name')
    .eq('id', userId)
    .single();

  const displayName =
    profile?.display_name ||
    [telegramUser.first_name, telegramUser.last_name].filter(Boolean).join(' ') ||
    'User';

  const exp = Date.now() + 2 * 60 * 1000; // 2-minute session handoff window
  const payload = Buffer.from(JSON.stringify({ userId, displayName, exp })).toString('base64url');
  const secret = env.NEXTAUTH_SECRET ?? env.SUPABASE_SERVICE_KEY;
  const sig = createHmac('sha256', secret).update(payload).digest('base64url');

  return NextResponse.json({ sessionToken: `${payload}.${sig}`, overLimit });
});
